apiVersion: v1
kind: Service
metadata:
  name: entry-light
  namespace: default
spec:
  selector:
    app: entry-light
  ports:
  - name: http
    port: 80 
    protocol: TCP
    targetPort: 8080 
  type: ClusterIP